(defconst *is-a-mac* (eq system-type 'darwin))
(add-to-list 'load-path (expand-file-name "lisp" user-emacs-directory))

(require 'init-benchmarking)
(require 'init-elpa)
(require 'init-utils)
(require 'init-desktop)
(require 'init-window)
(require 'init-exec-path)
(require 'init-themes)
(require 'init-uniquify)
(require 'init-flycheck)
(require 'init-recentf)
(require 'init-ido)
(require 'init-editing-utils)
(require 'init-yasnippet)
(require 'init-paredit)

(require 'init-markdown)
(require 'init-git)
(require 'init-python)
(require 'init-company)
(require 'init-go)
(require 'init-rust)
(require 'init-julia)
(require 'init-lisp)
(require 'init-ocaml)
(require 'init-haskell)
(require 'init-web)
(require 'init-helm)
(require 'init-org)
(require 'init-rfc)
